[package]
name = "NebulaOS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.28.0", features = ["panic_handler", "global_allocator"] }
uefi-graphics2 = "0.2.1"

hex = "0.4.3"
